### ISSUE TITLE
Command changes between 5.0.2 and 5.0.3

### ISSUE THREAD

**Issue by dcangulo** [seuros/capistrano-puma#318] opened 2021-02-28 15:36 UTC
After updating from 5.0.2 to 5.0.3, I encountered the following error during deployment.

```
INFO [7f302e6e] Running /usr/bin/env /bin/systemctl --user restart puma_app-name_production as deploy@ipaddress
 DEBUG [7f302e6e] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="3.0.0-preview2" ; /usr/bin/env /bin/systemctl --user restart puma_app-name_production )
 DEBUG [7f302e6e]   Failed to restart puma_app-name_production.service: Unit puma_app-name_production.service not found.
 DEBUG [7f302e6e]   
#<Thread:0x00007fe3413f7538 /Users/davidangulo/.rbenv/versions/3.0.0-preview2/lib/ruby/gems/3.0.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
```

Is there a breaking change between 5.0.2 and 5.0.3? Reverting to 5.0.2 fixes the problem for me.

I noticed that in 5.0.2 this is the executed command:
```
[daf3397e] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="3.0.0-preview2" ; /usr/bin/env sudo /bin/systemctl restart puma )
```

While in 5.0.3, this command changed to:
```
[7f302e6e] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="3.0.0-preview2" ; /usr/bin/env /bin/systemctl --user restart puma_app-name_production )
```

Is this a bug or an update to my config is needed? 

Thanks! 😊

**Comment by davegudge** [comment] 2021-03-03 12:29
Duplicate of https://github.com/seuros/capistrano-puma/issues/316

Fixed by #319

**Closed** 2021-03-03 12:43 UTC
